#!/usr/bin/env bash
# create-extensions.sh — Create FreePBX PJSIP extensions for hot-desk users
# Generated by services/phone-provisioning/generate.py — do not edit manually.
#
# Usage: sg docker -c "bash services/phone-provisioning/create-extensions.sh"

set -euo pipefail

CONTAINER="raspbx-core"
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

log() { echo -e "${GREEN}[OK]${NC} $*"; }
err() { echo -e "${RED}[ERR]${NC} $*" >&2; }

# Check container is running
if ! docker inspect "$CONTAINER" &>/dev/null; then
    err "Container $CONTAINER not found"
    exit 1
fi

# Extension 001 — Staff 001
echo "Creating extension 001 (Staff 001)..."
docker exec "$CONTAINER" bash -c '
    /var/lib/asterisk/bin/fwconsole ext --create \
        --ext="001" \
        --name="Staff 001" \
        --tech="pjsip" \
        --secret="change-me" 2>/dev/null || echo "Extension 001 may already exist"
'
# Extension 002 — Staff 002
echo "Creating extension 002 (Staff 002)..."
docker exec "$CONTAINER" bash -c '
    /var/lib/asterisk/bin/fwconsole ext --create \
        --ext="002" \
        --name="Staff 002" \
        --tech="pjsip" \
        --secret="change-me" 2>/dev/null || echo "Extension 002 may already exist"
'
# Extension 003 — Staff 003
echo "Creating extension 003 (Staff 003)..."
docker exec "$CONTAINER" bash -c '
    /var/lib/asterisk/bin/fwconsole ext --create \
        --ext="003" \
        --name="Staff 003" \
        --tech="pjsip" \
        --secret="change-me" 2>/dev/null || echo "Extension 003 may already exist"
'
# Extension 004 — Staff 004
echo "Creating extension 004 (Staff 004)..."
docker exec "$CONTAINER" bash -c '
    /var/lib/asterisk/bin/fwconsole ext --create \
        --ext="004" \
        --name="Staff 004" \
        --tech="pjsip" \
        --secret="change-me" 2>/dev/null || echo "Extension 004 may already exist"
'
# Extension 005 — Staff 005
echo "Creating extension 005 (Staff 005)..."
docker exec "$CONTAINER" bash -c '
    /var/lib/asterisk/bin/fwconsole ext --create \
        --ext="005" \
        --name="Staff 005" \
        --tech="pjsip" \
        --secret="change-me" 2>/dev/null || echo "Extension 005 may already exist"
'
# Extension 006 — Staff 006
echo "Creating extension 006 (Staff 006)..."
docker exec "$CONTAINER" bash -c '
    /var/lib/asterisk/bin/fwconsole ext --create \
        --ext="006" \
        --name="Staff 006" \
        --tech="pjsip" \
        --secret="change-me" 2>/dev/null || echo "Extension 006 may already exist"
'
# Extension 007 — Staff 007
echo "Creating extension 007 (Staff 007)..."
docker exec "$CONTAINER" bash -c '
    /var/lib/asterisk/bin/fwconsole ext --create \
        --ext="007" \
        --name="Staff 007" \
        --tech="pjsip" \
        --secret="change-me" 2>/dev/null || echo "Extension 007 may already exist"
'
# Extension 008 — Staff 008
echo "Creating extension 008 (Staff 008)..."
docker exec "$CONTAINER" bash -c '
    /var/lib/asterisk/bin/fwconsole ext --create \
        --ext="008" \
        --name="Staff 008" \
        --tech="pjsip" \
        --secret="change-me" 2>/dev/null || echo "Extension 008 may already exist"
'
# Extension 009 — Staff 009
echo "Creating extension 009 (Staff 009)..."
docker exec "$CONTAINER" bash -c '
    /var/lib/asterisk/bin/fwconsole ext --create \
        --ext="009" \
        --name="Staff 009" \
        --tech="pjsip" \
        --secret="change-me" 2>/dev/null || echo "Extension 009 may already exist"
'
# Extension 010 — Staff 010
echo "Creating extension 010 (Staff 010)..."
docker exec "$CONTAINER" bash -c '
    /var/lib/asterisk/bin/fwconsole ext --create \
        --ext="010" \
        --name="Staff 010" \
        --tech="pjsip" \
        --secret="change-me" 2>/dev/null || echo "Extension 010 may already exist"
'
# Extension 011 — Staff 011
echo "Creating extension 011 (Staff 011)..."
docker exec "$CONTAINER" bash -c '
    /var/lib/asterisk/bin/fwconsole ext --create \
        --ext="011" \
        --name="Staff 011" \
        --tech="pjsip" \
        --secret="change-me" 2>/dev/null || echo "Extension 011 may already exist"
'
# Extension 012 — Staff 012
echo "Creating extension 012 (Staff 012)..."
docker exec "$CONTAINER" bash -c '
    /var/lib/asterisk/bin/fwconsole ext --create \
        --ext="012" \
        --name="Staff 012" \
        --tech="pjsip" \
        --secret="change-me" 2>/dev/null || echo "Extension 012 may already exist"
'

# Reload FreePBX
echo "Reloading FreePBX..."
docker exec "$CONTAINER" /var/lib/asterisk/bin/fwconsole reload
log "All extensions created and FreePBX reloaded"
