apiVersion: v1
kind: Service
metadata:
  name: selenium-daemon
  namespace: shinbee
  labels:
    app.kubernetes.io/name: selenium-daemon
    app.kubernetes.io/component: browser-automation
    app.kubernetes.io/part-of: shinbee
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: selenium-daemon
  ports:
    - port: 8020
      targetPort: http
      protocol: TCP
      name: http
