apiVersion: v1
kind: Service
metadata:
  name: intranet-minio
  namespace: intranet
  labels:
    app.kubernetes.io/name: intranet-minio
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: shinbee-intranet
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: intranet-minio
  ports:
    - port: 9000
      targetPort: api
      protocol: TCP
      name: api
