apiVersion: v1
kind: Service
metadata:
  name: intranet-outline
  namespace: intranet
  labels:
    app.kubernetes.io/name: intranet-outline
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: shinbee-intranet
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: intranet-outline
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
