"""Asterisk config generator — reads SQLite PBX database, writes .conf files.

Generates:
  - pjsip_extensions.conf  (endpoint, auth, AOR for each extension)
  - extensions_generated.conf  (dialplan: routing, ring groups, day/night, feature codes, IVR)
  - voicemail_generated.conf  (voicemail boxes)

Preserved files (NOT generated, kept as-is):
  - pjsip_ntt_dynamic.conf  (NTT trunk — rendered by vault/faxapi DHCP handler)
  - extensions_custom.conf   (hand-written NTT/fax contexts)
  - pjsip.conf / pjsip.transports.conf  (transport config)
"""

import logging
import os
import sqlite3
import tempfile
from datetime import datetime
from pathlib import Path

log = logging.getLogger(__name__)

# Default paths — overridden in container environment
DEFAULT_DB_PATH = "/var/lib/asterisk/pbx.db"
DEFAULT_ASTERISK_DIR = "/etc/asterisk"


class ConfGen:
    """Generate Asterisk config files from SQLite PBX database."""

    def __init__(self, db_path: str = DEFAULT_DB_PATH, asterisk_dir: str = DEFAULT_ASTERISK_DIR):
        self.db_path = db_path
        self.asterisk_dir = asterisk_dir

    def _conn(self) -> sqlite3.Connection:
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row
        return conn

    # ------------------------------------------------------------------
    # PJSIP extensions config
    # ------------------------------------------------------------------

    def _gen_pjsip_extensions(self) -> str:
        """Generate pjsip_extensions.conf with endpoint/auth/aor for each extension."""
        conn = self._conn()
        extensions = conn.execute("SELECT * FROM extensions ORDER BY ext").fetchall()
        conn.close()

        lines = [
            f"; pjsip_extensions.conf — Auto-generated by confgen.py",
            f"; Generated: {datetime.now().isoformat()}",
            f"; Extensions: {len(extensions)}",
            f"; DO NOT EDIT — changes will be overwritten on next confgen run.",
            "",
        ]

        for ext in extensions:
            e = ext["ext"]
            name = ext["name"]
            pw = ext["password"]
            ctx = ext["context"]

            # Endpoint
            lines.append(f"[{e}]")
            lines.append("type=endpoint")
            lines.append("transport=0.0.0.0-udp")
            lines.append(f"aors={e}")
            lines.append(f"auth={e}-auth")
            lines.append("tos_audio=ef")
            lines.append("cos_audio=5")
            lines.append("allow=ulaw")
            lines.append(f"context={ctx}")
            lines.append(f'callerid={name} <{e}>')
            lines.append("dtmf_mode=rfc4733")
            lines.append("direct_media=yes")
            if ext["mailbox"]:
                lines.append(f"mailboxes={e}@device")
            lines.append("trust_id_inbound=yes")
            lines.append("send_pai=yes")
            lines.append("send_connected_line=yes")
            lines.append("rtp_symmetric=yes")
            lines.append("rewrite_contact=yes")
            lines.append("force_rport=yes")
            lines.append("language=ja")
            # Call/pickup groups for *8 (group pickup) and ** (directed pickup)
            call_grp = ext["call_group"] if ext["call_group"] else "1"
            pickup_grp = ext["pickup_group"] if ext["pickup_group"] else "1"
            lines.append(f"named_call_group={call_grp}")
            lines.append(f"named_pickup_group={pickup_grp}")
            if ext["recording"]:
                lines.append("one_touch_recording=on")
                lines.append("record_on_feature=apprecord")
                lines.append("record_off_feature=apprecord")
            lines.append("timers=yes")
            lines.append("timers_min_se=90")
            lines.append("rtp_timeout=30")
            lines.append("rtp_timeout_hold=300")
            lines.append("rtp_keepalive=0")
            lines.append("media_encryption=no")
            lines.append("")

            # Auth
            lines.append(f"[{e}-auth]")
            lines.append("type=auth")
            lines.append("auth_type=userpass")
            lines.append(f"password={pw}")
            lines.append(f"username={e}")
            lines.append("")

            # AOR
            lines.append(f"[{e}]")
            lines.append("type=aor")
            lines.append("max_contacts=1")
            lines.append("remove_existing=yes")
            lines.append("maximum_expiration=7200")
            lines.append("minimum_expiration=60")
            lines.append("qualify_frequency=60")
            if ext["mailbox"]:
                lines.append(f"mailboxes={e}@device")
            lines.append("")

        return "\n".join(lines) + "\n"

    # ------------------------------------------------------------------
    # Dialplan
    # ------------------------------------------------------------------

    def _gen_dialplan(self) -> str:
        """Generate extensions_generated.conf with all dialplan contexts."""
        conn = self._conn()

        lines = [
            f"; extensions_generated.conf — Auto-generated by confgen.py",
            f"; Generated: {datetime.now().isoformat()}",
            f"; DO NOT EDIT — changes will be overwritten on next confgen run.",
            "",
        ]

        # Globals
        lines.extend(self._gen_globals(conn))
        lines.append("")

        # from-internal: extension-to-extension dialing
        lines.extend(self._gen_from_internal(conn))
        lines.append("")

        # from-pstn: inbound DID routing
        lines.extend(self._gen_from_pstn(conn))
        lines.append("")

        # Outbound routes
        lines.extend(self._gen_outbound_routes(conn))
        lines.append("")

        # Ring groups
        lines.extend(self._gen_ring_groups(conn))
        lines.append("")

        # Day/night modes
        lines.extend(self._gen_day_night(conn))
        lines.append("")

        # IVR menus
        lines.extend(self._gen_ivr(conn))
        lines.append("")

        # Feature codes
        lines.extend(self._gen_feature_codes(conn))
        lines.append("")

        # Utility contexts (blackhole, recorded-call, etc.)
        lines.extend(self._gen_utility_contexts(conn))
        lines.append("")

        conn.close()
        return "\n".join(lines) + "\n"

    def _gen_globals(self, conn: sqlite3.Connection) -> list[str]:
        lines = [
            "[globals]",
            "; Trunk config",
            "TRUNK=PJSIP",
            "TRUNK_PEER=ntt-trunk",
            "OUTCID=0312345678",
            "DIAL_OPTIONS=HhTtr",
            "TRUNK_OPTIONS=T",
            "RINGTIMER=15",
            "TRANSFER_CONTEXT=from-internal-xfer",
        ]
        return lines

    def _gen_from_internal(self, conn: sqlite3.Connection) -> list[str]:
        """Internal extension dialing + feature code routing."""
        extensions = conn.execute("SELECT ext, name FROM extensions ORDER BY ext").fetchall()
        feature_codes = conn.execute("SELECT code, context FROM feature_codes WHERE enabled = 1").fetchall()

        lines = [
            "; === Internal dialing ===",
            "[from-internal]",
            "include => from-internal-custom",
            "include => ext-local",
            "include => outbound-allroutes",
            "include => ext-featurecodes",
            "include => ext-group",
            "include => app-pickup",
            "",
            "[from-internal-custom]",
            "; Placeholder for custom internal additions",
            "",
            "; --- Extension routing ---",
            "[ext-local]",
        ]

        for ext in extensions:
            e = ext["ext"]
            lines.append(f"exten => {e},1,NoOp(Dialing extension {e}: {ext['name']})")
            # Set PICKUPMARK for directed pickup (**XXX) and CALLTRACE for *32
            lines.append(f" same => n,Set(__PICKUPMARK=${{EXTEN}})")
            lines.append(f" same => n,Set(DB(CALLTRACE/${{CALLERID(num)}})=${{EXTEN}})")
            lines.append(f" same => n,Set(__RINGTIMER=${{DB(RINGTIMER/{e})}})")
            lines.append(f" same => n,GotoIf(${{LEN(${{RINGTIMER}})}}?:skip_rt)")
            lines.append(f" same => n,Set(DIAL_TIMER=${{RINGTIMER}})")
            lines.append(f" same => n(skip_rt),Set(DIAL_TIMER=${{IF(${{LEN(${{DIAL_TIMER}})}}?${{DIAL_TIMER}}:${{RINGTIMER}})}})")
            # Check call forward unconditional
            lines.append(f" same => n,Set(CFU=${{DB(CFU/{e})}})")
            lines.append(f" same => n,GotoIf(${{LEN(${{CFU}})}}?cf_redirect)")
            # Check call forward busy (set for later)
            lines.append(f" same => n,Set(__CFB=${{DB(CFB/{e})}})")
            lines.append(f" same => n,Set(__CFNA=${{DB(CFNA/{e})}})")
            # Dial the extension
            lines.append(f" same => n,Dial(PJSIP/{e},${{IF(${{LEN(${{DIAL_TIMER}})}}?${{DIAL_TIMER}}:15)}},Ttro(ntt-headers^s^1))")
            # Handle NOANSWER
            lines.append(f" same => n,GotoIf(${{LEN(${{CFNA}})}}?cf_noanswer)")
            lines.append(f" same => n,VoiceMail({e}@device,u)")
            lines.append(f" same => n,Hangup()")
            # Call forward redirect
            lines.append(f" same => n(cf_redirect),Goto(from-internal,${{CFU}},1)")
            lines.append(f" same => n(cf_noanswer),Goto(from-internal,${{CFNA}},1)")
            # Clear PICKUPMARK after call ends
            lines.append(f" same => n,Set(__PICKUPMARK=)")
            lines.append("")

        return lines

    def _gen_from_pstn(self, conn: sqlite3.Connection) -> list[str]:
        """Inbound DID routing (from-pstn is included by extensions.conf)."""
        routes = conn.execute("SELECT * FROM inbound_routes ORDER BY id").fetchall()

        lines = [
            "; === Inbound DID routing (from-pstn) ===",
            "; Note: [from-pstn] is defined in extensions.conf, which includes ext-did.",
            "; [from-ntt] in extensions_custom.conf parses NTT To header → from-pstn.",
            "",
            "[ext-did]",
        ]

        for route in routes:
            did = route["did"]
            dest = route["destination"]
            desc = route["description"] or ""

            if did == "default":
                # Catch-all: match any DID not explicitly routed
                lines.append(f"; Default route: {desc}")
                lines.append(f"exten => _X!,1,NoOp(Inbound DID ${{EXTEN}} — default route)")
                lines.append(f" same => n,Gosub(app-blacklist-check,s,1())")
                lines.append(f" same => n,GotoIf(${{BLACKLISTED}}?app-blackhole,hangup,1)")
                lines.append(f" same => n,Set(CALLERID(name-pres)=allowed)")
                lines.append(f" same => n,Goto({self._dest_to_context(dest)})")
                lines.append("")
                lines.append(f"exten => s,1,NoOp(Inbound DID (no exten) — default route)")
                lines.append(f" same => n,Gosub(app-blacklist-check,s,1())")
                lines.append(f" same => n,GotoIf(${{BLACKLISTED}}?app-blackhole,hangup,1)")
                lines.append(f" same => n,Goto({self._dest_to_context(dest)})")
                lines.append("")
            elif did == "0312345679":
                # Fax line — skip, handled by extensions_custom.conf [from-ntt]
                lines.append(f"; Fax DID {did} — handled by [from-ntt] in extensions_custom.conf")
                lines.append("")
            else:
                lines.append(f"; DID route: {did} → {dest} ({desc})")
                lines.append(f"exten => {did},1,NoOp(Inbound DID {did})")
                lines.append(f" same => n,Gosub(app-blacklist-check,s,1())")
                lines.append(f" same => n,GotoIf(${{BLACKLISTED}}?app-blackhole,hangup,1)")
                lines.append(f" same => n,Goto({self._dest_to_context(dest)})")
                lines.append("")

        return lines

    def _gen_outbound_routes(self, conn: sqlite3.Connection) -> list[str]:
        """Outbound route contexts — pattern matching for trunk routing."""
        routes = conn.execute("SELECT * FROM outbound_routes ORDER BY priority").fetchall()

        lines = [
            "; === Outbound routes ===",
            "[outbound-allroutes]",
        ]

        # Include each route context
        route_names = []
        for route in routes:
            ctx_name = f"outrt-{route['id']}"
            lines.append(f"include => {ctx_name}")
            route_names.append(ctx_name)
        lines.append("")

        for route in routes:
            ctx_name = f"outrt-{route['id']}"
            lines.append(f"; Route: {route['name']} (priority {route['priority']})")
            lines.append(f"[{ctx_name}]")

            pattern = route["pattern"]
            if route["action"] == "BLOCK":
                lines.append(f"exten => {pattern},1,NoOp(BLOCKED: {route['name']})")
                lines.append(f" same => n,Playback(ss-noservice)")
                lines.append(f" same => n,Congestion(20)")
                lines.append(f" same => n,Hangup()")
            else:
                # Strip leading 9 (external access code) for trunk dialing
                lines.append(f"exten => {pattern},1,NoOp(Outbound: {route['name']} via {route['trunk']})")
                pw = route["password"]
                if pw:
                    lines.append(f" same => n,Authenticate({pw})")
                lines.append(f" same => n,Set(OUTNUM=${{EXTEN:1}})")
                lines.append(f" same => n,Set(CALLERID(num)=0312345678)")
                lines.append(f" same => n,Dial(PJSIP/${{OUTNUM}}@{route['trunk']},300,Tb(ntt-headers^s^1))")
                lines.append(f" same => n,Hangup()")
            lines.append("")

        return lines

    def _gen_ring_groups(self, conn: sqlite3.Connection) -> list[str]:
        """Ring group contexts."""
        groups = conn.execute("SELECT * FROM ring_groups ORDER BY id").fetchall()

        lines = [
            "; === Ring groups ===",
            "[ext-group]",
        ]

        for group in groups:
            members = conn.execute(
                "SELECT ext FROM ring_group_members WHERE group_id = ? ORDER BY ext",
                (group["id"],),
            ).fetchall()
            member_list = [m["ext"] for m in members]

            num = group["number"]
            strategy = group["strategy"]
            timeout = group["timeout"]
            dest = group["destination"]

            lines.append(f"; Ring group {num}: {group['description']} ({strategy}, {timeout}s)")
            lines.append(f"exten => {num},1,NoOp(Ring group {num} — {strategy})")

            if strategy == "ringall":
                # Build PJSIP dial string: PJSIP/001&PJSIP/002&...
                dial_str = "&".join(f"PJSIP/{ext}" for ext in member_list)
                lines.append(f" same => n,Dial({dial_str},{timeout},Ttrg)")
            else:
                # Hunt / sequential: dial one by one
                for ext in member_list:
                    lines.append(f" same => n,Dial(PJSIP/{ext},{timeout // len(member_list)},Ttr)")

            # Fallback
            if dest == "hangup":
                lines.append(f" same => n,Hangup()")
            elif dest.startswith("ivr-"):
                ivr_id = dest.split("-", 1)[1]
                lines.append(f" same => n,Goto(ivr-{ivr_id},s,1)")
            else:
                lines.append(f" same => n,Goto({self._dest_to_context(dest)})")
            lines.append("")

        return lines

    def _gen_day_night(self, conn: sqlite3.Connection) -> list[str]:
        """Day/night mode contexts with DB-driven toggle."""
        modes = conn.execute("SELECT * FROM day_night_modes ORDER BY id").fetchall()

        lines = [
            "; === Day/Night modes ===",
            "[app-daynight]",
        ]

        for mode in modes:
            mid = mode["id"]
            day_dest = mode["day_destination"]
            night_dest = mode["night_destination"]
            # FreePBX uses "C" prefix for AstDB keys: DAYNIGHT/C0, DAYNIGHT/C1, etc.
            db_key = f"C{mid}"

            lines.append(f"; Mode {mid}: {mode['name']}")
            lines.append(f"exten => {mid},1,NoOp(Day/Night mode {mid}: {mode['name']})")
            lines.append(f" same => n,Set(DAYNIGHT=${{DB(DAYNIGHT/{db_key})}})")
            lines.append(f" same => n,GotoIf($[${{LEN(${{DAYNIGHT}})}} = 0]?day)")
            lines.append(f" same => n,GotoIf($[${{DAYNIGHT}} = NIGHT]?night:day)")
            lines.append(f" same => n(day),Goto({self._dest_to_context(day_dest)})")
            lines.append(f" same => n(night),Goto({self._dest_to_context(night_dest)})")
            lines.append("")

        # Toggle context
        lines.append("; Day/Night toggle (feature codes *280, *281, *282)")
        lines.append("[app-daynight-toggle]")
        for mode in modes:
            mid = mode["id"]
            pw = mode["password"]
            db_key = f"C{mid}"
            lines.append(f"exten => *28{mid},1,NoOp(Toggle day/night mode {mid})")
            if pw:
                lines.append(f" same => n,Authenticate({pw})")
            lines.append(f" same => n,Set(CURRENT=${{DB(DAYNIGHT/{db_key})}})")
            lines.append(f" same => n,GotoIf($[${{CURRENT}} = NIGHT]?set_day)")
            lines.append(f" same => n,Set(DB(DAYNIGHT/{db_key})=NIGHT)")
            lines.append(f" same => n,Playback(beep)")
            lines.append(f" same => n,Hangup()")
            lines.append(f" same => n(set_day),Set(DB(DAYNIGHT/{db_key})=DAY)")
            lines.append(f" same => n,Playback(beep)")
            lines.append(f" same => n,Hangup()")
            lines.append("")

        return lines

    def _gen_ivr(self, conn: sqlite3.Connection) -> list[str]:
        """IVR menu contexts."""
        menus = conn.execute("SELECT * FROM ivr_menus ORDER BY id").fetchall()

        lines = ["; === IVR Menus ==="]

        for menu in menus:
            mid = menu["id"]
            entries = conn.execute(
                "SELECT digit, destination FROM ivr_entries WHERE ivr_id = ? ORDER BY digit",
                (mid,),
            ).fetchall()

            lines.append(f"; IVR {mid}: {menu['name']} — {menu['description']}")
            lines.append(f"[ivr-{mid}]")
            lines.append(f"exten => s,1,NoOp(IVR {mid}: {menu['name']})")
            lines.append(f" same => n,Answer()")
            lines.append(f" same => n(start),Set(TIMEOUT(response)={menu['timeout']})")
            # Play IVR greeting — use audio_file from DB, fallback to custom/ivr-{id}
            audio = menu["audio_file"] if menu["audio_file"] else f"custom/ivr-{mid}"
            lines.append(f" same => n,Background({audio})")
            lines.append(f" same => n,WaitExten({menu['timeout']})")
            lines.append("")

            # Digit entries
            for entry in entries:
                dest = self._dest_to_context(entry["destination"])
                lines.append(f"exten => {entry['digit']},1,Goto({dest})")
            lines.append("")

            # Timeout
            timeout_dest = menu["timeout_destination"]
            if timeout_dest:
                lines.append(f"exten => t,1,Goto({self._dest_to_context(timeout_dest)})")
            else:
                lines.append(f"exten => t,1,Goto(s,start)")
            lines.append("")

            # Invalid
            invalid_dest = menu["invalid_destination"]
            if invalid_dest:
                lines.append(f"exten => i,1,Goto({self._dest_to_context(invalid_dest)})")
            else:
                lines.append(f"exten => i,1,Goto(s,start)")
            lines.append("")

        return lines

    def _gen_feature_codes(self, conn: sqlite3.Connection) -> list[str]:
        """Feature code contexts."""
        codes = conn.execute("SELECT * FROM feature_codes WHERE enabled = 1 ORDER BY code").fetchall()

        lines = [
            "; === Feature codes ===",
            "[ext-featurecodes]",
        ]

        for fc in codes:
            code = fc["code"]
            ctx = fc["context"]
            lines.append(f"exten => {code},1,Goto({ctx},{code},1)")

        lines.append("")

        # Voicemail
        lines.extend(self._gen_vmail_contexts())
        lines.append("")

        # Call forward on/off
        lines.extend(self._gen_cf_contexts())
        lines.append("")

        # Blacklist
        lines.extend(self._gen_blacklist_contexts())
        lines.append("")

        # Pickup
        lines.extend(self._gen_pickup_contexts(conn))
        lines.append("")

        # Call waiting
        lines.extend(self._gen_cw_contexts())
        lines.append("")

        return lines

    def _gen_vmail_contexts(self) -> list[str]:
        """Voicemail login/direct feature code contexts."""
        return [
            "; --- Voicemail ---",
            "[app-vmail-login]",
            "exten => *98,1,NoOp(Voicemail Login)",
            " same => n,VoiceMailMain(@device)",
            " same => n,Hangup()",
            "",
            "[app-vmail-direct]",
            "exten => *97,1,NoOp(Voicemail Direct Check)",
            " same => n,VoiceMailMain(${CALLERID(num)}@device,s)",
            " same => n,Hangup()",
        ]

    def _gen_cf_contexts(self) -> list[str]:
        """Call forwarding feature code contexts."""
        return [
            "; --- Call Forward Unconditional ---",
            "[app-cf-on]",
            "exten => *72,1,NoOp(Enable Call Forward)",
            " same => n,Read(CFNUM,followme/options&vm-enter-num-to-call,,,,)",
            " same => n,GotoIf($[${LEN(${CFNUM})} = 0]?hangup)",
            " same => n,Set(DB(CFU/${CALLERID(num)})=${CFNUM})",
            " same => n,Playback(beep)",
            " same => n,Hangup()",
            " same => n(hangup),Hangup()",
            "",
            "[app-cf-off]",
            "exten => *73,1,NoOp(Disable Call Forward)",
            " same => n,DBdel(CFU/${CALLERID(num)})",
            " same => n,Playback(beep)",
            " same => n,Hangup()",
            "",
            "; --- Call Forward Busy ---",
            "[app-cf-busy-on]",
            "exten => *90,1,NoOp(Enable Call Forward Busy)",
            " same => n,Read(CFBNUM,followme/options&vm-enter-num-to-call,,,,)",
            " same => n,GotoIf($[${LEN(${CFBNUM})} = 0]?hangup)",
            " same => n,Set(DB(CFB/${CALLERID(num)})=${CFBNUM})",
            " same => n,Playback(beep)",
            " same => n,Hangup()",
            " same => n(hangup),Hangup()",
            "",
            "[app-cf-busy-off]",
            "exten => *91,1,NoOp(Disable Call Forward Busy)",
            " same => n,DBdel(CFB/${CALLERID(num)})",
            " same => n,Playback(beep)",
            " same => n,Hangup()",
            "",
            "; --- Call Forward No Answer ---",
            "[app-cf-noanswer-on]",
            "exten => *52,1,NoOp(Enable Call Forward No Answer)",
            " same => n,Read(CFNANUM,followme/options&vm-enter-num-to-call,,,,)",
            " same => n,GotoIf($[${LEN(${CFNANUM})} = 0]?hangup)",
            " same => n,Set(DB(CFNA/${CALLERID(num)})=${CFNANUM})",
            " same => n,Playback(beep)",
            " same => n,Hangup()",
            " same => n(hangup),Hangup()",
            "",
            "[app-cf-noanswer-off]",
            "exten => *53,1,NoOp(Disable Call Forward No Answer)",
            " same => n,DBdel(CFNA/${CALLERID(num)})",
            " same => n,Playback(beep)",
            " same => n,Hangup()",
        ]

    def _gen_blacklist_contexts(self) -> list[str]:
        """Blacklist feature code contexts."""
        return [
            "; --- Blacklist ---",
            "[app-blacklist-add]",
            "exten => *30,1,NoOp(Add to blacklist)",
            " same => n,Read(BLNUM,vm-enter-num-to-call,,,,)",
            " same => n,GotoIf($[${LEN(${BLNUM})} = 0]?hangup)",
            " same => n,Set(DB(blacklist/${BLNUM})=1)",
            " same => n,Playback(beep)",
            " same => n,Hangup()",
            " same => n(hangup),Hangup()",
            "",
            "[app-blacklist-remove]",
            "exten => *31,1,NoOp(Remove from blacklist)",
            " same => n,Read(BLNUM,vm-enter-num-to-call,,,,)",
            " same => n,GotoIf($[${LEN(${BLNUM})} = 0]?hangup)",
            " same => n,DBdel(blacklist/${BLNUM})",
            " same => n,Playback(beep)",
            " same => n,Hangup()",
            " same => n(hangup),Hangup()",
            "",
            "[app-blacklist-last]",
            "exten => *32,1,NoOp(Blacklist last caller)",
            " same => n,Set(LASTCALLER=${DB(CALLTRACE/${CALLERID(num)})})",
            " same => n,GotoIf($[${LEN(${LASTCALLER})} = 0]?hangup)",
            " same => n,Set(DB(blacklist/${LASTCALLER})=1)",
            " same => n,Playback(beep)",
            " same => n,Hangup()",
            " same => n(hangup),Playback(beep)",
            " same => n,Hangup()",
        ]

    def _gen_pickup_contexts(self, conn: sqlite3.Connection) -> list[str]:
        """Call pickup contexts using named groups and PICKUPMARK."""
        extensions = conn.execute("SELECT ext FROM extensions ORDER BY ext").fetchall()

        lines = [
            "; --- Pickup ---",
            "[app-pickup]",
            "exten => *8,1,NoOp(Group Pickup — picks up any ringing call in named_pickup_group)",
            " same => n,Pickup()",
            " same => n,Hangup()",
            "",
            "[app-directed-pickup]",
            "; Generic pattern: **XXX picks up extension XXX by PICKUPMARK",
            "exten => _**.,1,NoOp(Directed Pickup ${EXTEN:2})",
            " same => n,Pickup(${EXTEN:2}&${EXTEN:2}@PICKUPMARK)",
            " same => n,Hangup()",
        ]

        # Per-extension directed pickup entries (matches FreePBX behavior)
        # These include ring group context in pickup targets for reliability
        for ext in extensions:
            e = ext["ext"]
            lines.append(f"exten => **{e},1,NoOp(Directed Pickup {e})")
            lines.append(f" same => n,Pickup({e}&{e}@PICKUPMARK&200@from-internal&200@ext-group)")
            lines.append(f" same => n,Hangup()")

        lines.append("")
        return lines

    def _gen_cw_contexts(self) -> list[str]:
        """Call waiting toggle contexts."""
        return [
            "; --- Call Waiting ---",
            "[app-cw-on]",
            "exten => *70,1,NoOp(Enable Call Waiting)",
            " same => n,Set(DB(CW/${CALLERID(num)})=ENABLED)",
            " same => n,Playback(beep)",
            " same => n,Hangup()",
            "",
            "[app-cw-off]",
            "exten => *71,1,NoOp(Disable Call Waiting)",
            " same => n,DBdel(CW/${CALLERID(num)})",
            " same => n,Playback(beep)",
            " same => n,Hangup()",
        ]

    def _gen_utility_contexts(self, conn: sqlite3.Connection) -> list[str]:
        """Utility contexts: blackhole, blacklist-check, recorded-call, announcements."""
        lines = [
            "; === Utility contexts ===",
            "",
            "; Blacklist check subroutine — called from from-pstn via Gosub",
            "[app-blacklist-check]",
            "exten => s,1,GotoIf($[${BLACKLIST()}=1]?blacklisted)",
            " same => n,Set(BLACKLISTED=0)",
            " same => n,Return()",
            " same => n(blacklisted),NoOp(Caller ${CALLERID(num)} is blacklisted)",
            " same => n,Set(BLACKLISTED=1)",
            " same => n,Return()",
            "",
            "; Blackhole destinations",
            "[app-blackhole]",
            "exten => hangup,1,Hangup()",
            "exten => zapateller,1,Zapateller()",
            " same => n,Hangup()",
            "exten => musiconhold,1,Answer()",
            " same => n,MusicOnHold()",
            "exten => congestion,1,Congestion(20)",
            " same => n,Hangup()",
            "exten => busy,1,Busy(20)",
            " same => n,Hangup()",
            "exten => ring,1,Answer()",
            " same => n,Ringing()",
            " same => n,Wait(300)",
            " same => n,Hangup()",
            "",
        ]

        # Announcements — read from DB
        announcements = conn.execute(
            "SELECT id, description, recording_file, post_dest FROM announcements ORDER BY id"
        ).fetchall()
        for ann in announcements:
            aid = ann["id"]
            recording = ann["recording_file"]
            post_dest = ann["post_dest"] or "hangup"
            lines.append(f"; Announcement {aid}: {ann['description']}")
            lines.append(f"[app-announcement-{aid}]")
            lines.append(f"exten => s,1,Answer()")
            lines.append(f" same => n,Playback({recording})")
            if post_dest == "hangup":
                lines.append(f" same => n,Hangup()")
            else:
                lines.append(f" same => n,Goto({self._dest_to_context(post_dest)})")
            lines.append("")

        lines.extend([
            "; Recorded call context (for ai_assistant call request)",
            "[recorded-call]",
            "exten => _X!,1,NoOp(Recorded call to ${EXTEN} — call_id=${CALL_ID})",
            " same => n,Answer()",
            " same => n,MixMonitor(${RECORDING_PATH},b)",
            " same => n,Dial(PJSIP/${EXTEN},60,Ttr)",
            " same => n,StopMixMonitor()",
            " same => n,Hangup()",
            "",
            "; Transfer contexts",
            "[from-internal-xfer]",
            "include => from-internal",
            "",
            "[app-transfer-blind]",
            "exten => ##,1,NoOp(Blind Transfer)",
            " same => n,Hangup()",
            "",
            "[app-transfer-attended]",
            "exten => *2,1,NoOp(Attended Transfer)",
            " same => n,Hangup()",
            "",
            "; Recording toggle (bound to apprecord feature)",
            "[app-recording-toggle]",
            "exten => *1,1,NoOp(One-touch recording toggle)",
            " same => n,Set(DYNAMIC_FEATURES=apprecord)",
            " same => n,Playback(beep)",
            " same => n,Hangup()",
        ])

        return lines

    def _dest_to_context(self, dest: str) -> str:
        """Convert destination shorthand to Asterisk context,exten,priority."""
        if not dest:
            return "app-blackhole,hangup,1"

        if dest.startswith("ivr-"):
            ivr_id = dest.split("-", 1)[1]
            return f"ivr-{ivr_id},s,1"
        if dest.startswith("ringgroup-"):
            num = dest.split("-", 1)[1]
            return f"ext-group,{num},1"
        if dest.startswith("daynight-"):
            mid = dest.split("-", 1)[1]
            return f"app-daynight,{mid},1"
        if dest.startswith("announcement-"):
            aid = dest.split("-", 1)[1]
            return f"app-announcement-{aid},s,1"
        if dest == "fax":
            return "fax-iax,s,1"
        if dest == "hangup":
            return "app-blackhole,hangup,1"

        # Assume it's already a context,exten,priority triple
        if "," in dest:
            return dest
        return f"{dest},s,1"

    # ------------------------------------------------------------------
    # Voicemail
    # ------------------------------------------------------------------

    def _gen_voicemail(self) -> str:
        """Generate voicemail_generated.conf."""
        conn = self._conn()
        extensions = conn.execute(
            "SELECT ext, name FROM extensions WHERE mailbox = 1 ORDER BY ext"
        ).fetchall()
        conn.close()

        lines = [
            f"; voicemail_generated.conf — Auto-generated by confgen.py",
            f"; Generated: {datetime.now().isoformat()}",
            "",
            "[device]",
        ]

        for ext in extensions:
            # Format: ext => password,name,email,pager,options
            lines.append(f"{ext['ext']} => ,{ext['name']},,,"
                         f"attach=yes|envelope=yes|delete=no|saycid=yes")

        return "\n".join(lines) + "\n"

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate_all(self) -> dict[str, str]:
        """Generate all config files, return {filename: content}."""
        return {
            "pjsip_extensions.conf": self._gen_pjsip_extensions(),
            "extensions_generated.conf": self._gen_dialplan(),
            "voicemail_generated.conf": self._gen_voicemail(),
        }

    def write_configs(self) -> list[str]:
        """Write generated configs to disk. Returns list of files written."""
        configs = self.generate_all()
        written = []
        for filename, content in configs.items():
            path = os.path.join(self.asterisk_dir, filename)
            # Atomic write
            fd, temp_path = tempfile.mkstemp(dir=self.asterisk_dir, suffix=".tmp")
            try:
                os.write(fd, content.encode())
                os.close(fd)
                os.chmod(temp_path, 0o644)
                # Set ownership to asterisk user if running as root
                try:
                    import pwd
                    pw = pwd.getpwnam("asterisk")
                    os.chown(temp_path, pw.pw_uid, pw.pw_gid)
                except (KeyError, PermissionError):
                    pass
                os.rename(temp_path, path)
                written.append(path)
                log.info("Wrote %s (%d bytes)", path, len(content))
            except Exception:
                os.close(fd) if not os.get_inheritable(fd) else None
                if os.path.exists(temp_path):
                    os.unlink(temp_path)
                raise
        return written

    def write_and_reload(self, ami_command_fn) -> dict:
        """Write configs to disk and reload Asterisk via AMI.

        Args:
            ami_command_fn: function that sends AMI command dict → response string

        Returns:
            {"files_written": [...], "reload_responses": [...]}
        """
        written = self.write_configs()

        reload_responses = []
        try:
            resp = ami_command_fn({"Action": "Command", "Command": "dialplan reload"})
            reload_responses.append(f"dialplan: {resp.strip()[:200]}")
        except Exception as exc:
            reload_responses.append(f"dialplan reload failed: {exc}")

        try:
            resp = ami_command_fn({"Action": "Command", "Command": "module reload res_pjsip.so"})
            reload_responses.append(f"pjsip: {resp.strip()[:200]}")
        except Exception as exc:
            reload_responses.append(f"pjsip reload failed: {exc}")

        return {
            "files_written": written,
            "reload_responses": reload_responses,
        }


# ------------------------------------------------------------------
# CLI entry point for testing
# ------------------------------------------------------------------

if __name__ == "__main__":
    import argparse

    logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")

    parser = argparse.ArgumentParser(description="Generate Asterisk configs from SQLite")
    parser.add_argument("--db", default=DEFAULT_DB_PATH, help="SQLite DB path")
    parser.add_argument("--output-dir", default=".", help="Output directory for config files")
    parser.add_argument("--diff", action="store_true", help="Show diff against existing files")
    args = parser.parse_args()

    gen = ConfGen(db_path=args.db, asterisk_dir=args.output_dir)
    configs = gen.generate_all()

    for filename, content in configs.items():
        path = os.path.join(args.output_dir, filename)
        with open(path, "w") as f:
            f.write(content)
        print(f"Wrote {path} ({len(content)} bytes, {content.count(chr(10))} lines)")
