apiVersion: v1
kind: Service
metadata:
  name: inventree-server
  namespace: shinbee
  labels:
    app.kubernetes.io/name: inventree-server
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: shinbee
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: inventree-server
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
