apiVersion: v1
kind: Service
metadata:
  name: phone-provision
  namespace: shinbee
  labels:
    app.kubernetes.io/name: phone-provision
  annotations:
    metallb.universe.tf/loadBalancerIPs: "10.0.0.251"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: phone-provision
  ports:
    - name: http
      port: 9080
      targetPort: 80
