apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-assistant-data
  namespace: shinbee
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-single
  resources:
    requests:
      storage: 100Mi
