apiVersion: v1
kind: Service
metadata:
  name: ai-assistant
  namespace: shinbee
  labels:
    app.kubernetes.io/name: ai-assistant
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8030
      targetPort: http
  selector:
    app.kubernetes.io/name: ai-assistant
