apiVersion: v1
kind: Service
metadata:
  name: samba-fileserver-lb
  namespace: shinbee
  annotations:
    metallb.universe.tf/loadBalancerIPs: "10.0.0.249"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: samba-fileserver
  ports:
    - name: smb
      port: 445
      targetPort: 445
      protocol: TCP
