[profiles]
    path = /srv/samba/profiles
    browseable = no
    read only = no
    store dos attributes = yes
    vfs objects = acl_xattr
    create mask = 0600
    directory mask = 0700

[shared]
    path = /srv/samba/shared
    browseable = yes
    read only = no
    valid users = @"SHINBEE\Domain Users"
    vfs objects = acl_xattr recycle
    recycle:repository = .recycle/%U
    recycle:keeptree = yes
    recycle:versions = yes
    recycle:touch = yes
    create mask = 0660
    directory mask = 0770
