---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: asterisk-etc
  namespace: fax-system
  labels:
    app.kubernetes.io/name: asterisk
    app.kubernetes.io/part-of: shinbee-fax
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn-single
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: asterisk-lib
  namespace: fax-system
  labels:
    app.kubernetes.io/name: asterisk
    app.kubernetes.io/part-of: shinbee-fax
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn-single
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: asterisk-spool
  namespace: fax-system
  labels:
    app.kubernetes.io/name: asterisk
    app.kubernetes.io/part-of: shinbee-fax
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn-single
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: asterisk-log
  namespace: fax-system
  labels:
    app.kubernetes.io/name: asterisk
    app.kubernetes.io/part-of: shinbee-fax
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn-single
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hylafax-spool
  namespace: fax-system
  labels:
    app.kubernetes.io/name: asterisk
    app.kubernetes.io/part-of: shinbee-fax
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn-single
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mail2fax-queue
  namespace: fax-system
  labels:
    app.kubernetes.io/name: mail2fax
    app.kubernetes.io/part-of: shinbee-fax
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn-single
  resources:
    requests:
      storage: 256Mi
