apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flutter-build-cache
  namespace: shinbee
  labels:
    app.kubernetes.io/name: flutter-builder
    app.kubernetes.io/component: cache
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-single
  resources:
    requests:
      storage: 5Gi
